name: UIEffectSnapshotDemo

on:
  push:
    branches:
      - main
    paths:
      - 'UIEffectSnapshotDemo/**'
      - '.github/workflows/UIEffectSnapshotDemo.yml'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2020_1_5 }}
  projectPath: UIEffectSnapshotDemo
  unityVersion: 2019.4.10f1
  targetPlatform: WebGL

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: ${{ env.projectPath }}/Library
          key: Library-${{ env.projectPath }}-${{ env.unityVersion }}-${{ env.WebGL }}

      - uses: webbertakken/unity-builder@v1.5
        with:
          projectPath: ${{ env.projectPath }}
          unityVersion: ${{ env.unityVersion }}
          targetPlatform: ${{ env.targetPlatform }}
          buildMethod: SimpleBuildInterface.Build
          customParameters: '-out /tmp/unity_build'

      - uses: actions/upload-artifact@v2
        with:
          path: /tmp/unity_build

      # - name: Commit files
      #   shell: bash -xe {0}
      #   run: |
      #     # clean checkout
      #     git checkout -f gh-pages && git clean -fd

      #     # update build path
      #     rm -rf ${{ env.projectPath }} && mv /tmp/unity_build ${{ env.projectPath }}

      #     # commit
      #     git add ${{ env.projectPath }}
      #     git commit -a -m 'chore: auto deploy ${{ env.projectPath }}'

      # - uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ github.token }}
      #     branch: gh-pages
